### ISSUE TITLE
Association 

### ISSUE THREAD

**Issue by houmanka** [danhper/seedex#1]
Hi. Thank you for the plugin. 

Can you please let me know how to implement association in my seed file? Or is it possible? 

Thanks

**Comment by danhper** [comment]
I simply use specify the ids to do this, but there is not anything in particular to do this.
Please look at the files here if you want an example.
https://github.com/tuvistavie/opencov/tree/master/priv/repo/seeds/eyecatch  
`build` belongs to `project`, `job` belongs to `build` and `file` belongs to job, so I specify the order using filename and add the ID explicitly.

If you would like to send a PR to improve association handling, I am very open.

Thanks.

**Comment by houmanka** [comment]
Thank you, will do.

Cheers
