### ISSUE TITLE
after a migration (change column name), seed return errors

### ISSUE THREAD

**Issue by lohayon** [danhper/seedex#2]
I had a table with a`provider` column
I renamed my column `provider_id`
I empty my table
I ran `mix seedex.seed` and i get 
```
** (Postgrex.Error) ERROR 42703 (undefined_column): column p0.provider does not exist
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
    (seedex) lib/seedex.ex:61: Seedex.insert_seed/4
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
```

**Comment by danhper** [comment]
seedex does not use any kind of cache, so I think you probably still have a reference to the `provider` column somewhere in your seed files.
If it does not seem to be the case, could you please provide a minimum sample to reproduce the error?
Thank you.

**Comment by lohayon** [comment]
I actually had a well hidden reference to the provider column in my app.
So, there is no bug.
Seedex is a very useful and easy to use feature.
Thank you
