### ISSUE TITLE
Changeset of schema is not used in inserts

### ISSUE THREAD

**Issue by lud** [danhper/seedex#3]
Hi, 

It could be nice if the seed function could call the changeset function when creating new records from list of maps.

I know I could use a function, but for each record this would be very verbose.

**Comment by lud** [comment]
Currently i do this :

```
data = [
  %{field1: "stuff",
    field2: "other stuff"}
]
|> Enum.map(& Thing.changeset(%Thing{}, &1))
|> Enum.map(&Ecto.Changeset.apply_changes(&1))
|> Enum.map(&Map.from_struct/1)

seed_once Thing, [:field1], data
```

**Comment by danhper** [comment]
I just published a new version which should allow you to do this more easily.
Now you can just write:

```elixir
data = [
  %{field1: "stuff",
    field2: "other stuff"}
]

seed_once Thing, [:field1], data, &Ecto.Changeset.apply_changes/1
```

or pass any other function as the last parameter and it will apply it after having transformed the `map` into a `struct`

**Comment by lud** [comment]
Thank you very much, I'll try it as soon as possible
